dist: xenial
addons:
  apt:
    sources:
    - sourceline: 'ppa:dns-oarc/dnscap-pr'
    update: true
    packages:
    - libpcap-dev
    - libldns-dev
    - libyaml-perl
    - zlib1g-dev
    - libssl-dev
    - libcryptopant-dev
language: c
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - ./configure --enable-warn-all
  - make dist
  - tar zxvf *.tar.gz
  - cd dnscap-[0-9]*
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - make test
  - src/dnscap -h
