dist: xenial
env:
  global:
   - secure: "HIpT8MM3W/9D8bLox3y/TuYUvKpzJQ8ddjJUdNB3xPkZ2O0K0zLN5I56rJCxIiwQlvcJ6fajbXdyrK+SN+SSjjvGyiP20F4FOQZaMnvkPbcSzEHn6LIu+WTlJhtFW5ZFlTrQ3fFfjhd36C9++u3Fi8877cOgVxrxhU/IRLP+xes="
addons:
  apt:
    sources:
    - sourceline: 'ppa:dns-oarc/dnscap-pr'
    update: true
    packages:
    - libpcap-dev
    - libldns-dev
    - libyaml-perl
    - zlib1g-dev
    - libssl-dev
    - libcryptopant-dev
  coverity_scan:
    project:
      name: "DNS-OARC/dnscap"
      description: "Build submitted via Travis CI"
    notification_email: lundstrom.jerry@gmail.com
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
language: c
compiler:
  - gcc
script: true
